version: "3"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: ketabdoozak
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            TZ: Asia/Tehran
        ports:
            - 5432:5432

    minio:
        image: minio/minio
        command: server /data
        ports:
            - 9000:9000
        environment:
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: minio_secret_key

    core:
        image: golang
        volumes:
            - $GOPATH/src/github.com/ketabdoozak/backend:/go/src/github.com/ketabdoozak/backend
        working_dir: /go/src/github.com/ketabdoozak/backend
        command: 'make run'
        ports:
            - 8080:8080
        environment:
            ENV: development
            DATABASE_URI: postgres://admin:admin@postgres:5432/ketabdoozak?sslmode=disable
            SERVER_ADDRESS: 0.0.0.0:8080
            GOBIN: /go/bin
            MINIO_SECURE: 0
            MINIO_ENDPOINT: minio:9000
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: minio_secret_key
            MINIO_BUCKET_NAME: assets
            MINIO_BUCKET_LOCATION: main
        depends_on:
            - postgres
            - minio
        links:
            - postgres
            - minio

    web:
        image: node
        ports:
            - 3000:3000
        volumes:
            - $GOPATH/src/github.com/ketabdoozak/web:/src
        environment:
            ENV: development
        working_dir: /src
        command: yarn run dev
        depends_on:
            - core
